
name: 'my_dbt_package'
version: '1.0.0'


profile: course


model-paths: ["models"]

test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]


clean-targets:
  - "target"
  - "dbt_packages"



models:
  my_dbt_package:
    example:
      +materialized: view
